import sys
import numpy as np

# Script for finding the median of numbers in an output file
# generated by test_cpd_recovery.py.
# Ignore for any other purpose.

a=list(map(float, open(sys.argv[1]).read().split('\n')[:-1]))
print(np.median(a))
